transactions = {
#================================================================================================
# EVENT TYPE: AMENDMENT
#================================================================================================
#>>> Count: True
"A..." : ["Response after Non-Final Action", True, "RESPONSE"], 
"SA.." : ["Supplemental Response", True, "SUPP RESPONSE"], 
"A.NA" : ["Amendment after Notice of Allowance (Rule 312)", True, "RESPONSE"], 
"A.NE" : ["Response after Final Action", True, "RESPONSE"], 
"ELC." : ["Response to Election / Restriction Filed", True, "RESPONSE"], 
"A.QU" : ["Response after Ex Parte Quayle Action", True, "RESPONSE"], 
"AABR" : ["Amendment After Brief", True, "RESPONSE"], 
"AP/A" : ["Amendment/Argument after Notice of Appeal", True, "RESPONSE"], 
"BD.A" : ["Amendment/Argument after BPAI Decision", True, "RESPONSE"], 
"TI1054" : ["Request for Classification Division Decision", True, "CLASSIFICATION INQUIRY"], 
"REAS" : ["Response to Reasons for Allowance", True, "RESPONSE NOA"], 
"A.I." : ["Informal or Non-Responsive Amendment after Examiner Action", True, "NON-COMPLIANT"], 
"A.LA" : ["Untimely (Late) Amendment Filed", True, "NON-COMPLIANT"], 
"WIDS" : ["Information Disclosure Statement (IDS) Filed", True, "IDS"], 
"DIST" : ["Terminal Disclaimer Filed", True, "TERMINAL DISCLAIMER"], 
"TK1R" : ["Track 1 Request", True, "TRACK ONE REQUEST"], 
"NPRQ" : ["PGPubs nonPub Request", True, "NON-PUB REQUEST"], 
"RESC" : ["Rescind Nonpublication Request for Pre Grant Publication", True, "NON-PUB REQUEST WITHDRAWN"], 
"PA.." : ["Change in Power of Attorney (May Include Associate POA)", True, "POWER OF ATTORNEY"], 

#>>> Count: False
"A.IX" : ["Withdraw of Informal Amendment Notice", False], 
"A.NQ" : ["Amendment Crossed in Mail", False], 
"TI1052" : ["Decision Made by Classification Division", False], 
"TI10XX" : ["Record Classification Panel Decision", False], 
"TI10XY" : ["Request Classification Panel Decision", False], 
"TI1050" : ["Transfer Inquiry to GAU", False], 

#================================================================================================
# EVENT TYPE: MISSING PARTS
#================================================================================================
#>>> Count: True
"INC/" : ["Notice of Incomplete Application - Filing Date Not Assigned", True, "MISSING PARTS"], 
"INCD" : ["Notice Mailed--Application Incomplete--Filing Date Assigned ", True, "MISSING PARTS"], 

#>>> Count: False
"INCR" : ["Notice of Incomplete Reply", False], 

#================================================================================================
# EVENT TYPE: PETITION
#================================================================================================
#>>> Count: True
"P002" : ["Record Petition Decision of Granted to Suspend an Action", True, "PETITION: WON"], 
"P003" : ["Record Petition Decision of Granted to Make Special", True, "PETITION: WON"], 
"P005" : ["Record Petition Decision of Granted to Accept Delayed Payment of Issue Fee", True, "PETITION: WON"], 
"P006" : ["Record Petition Decision of Granted to Withdraw from Issue", True, "PETITION: WON"], 
"P015" : ["Record Petition Decision of Granted to Withdraw from Issue - with assigned Patent NO.", True, "PETITION: WON"], 
"P023" : ["Record a Petition Decision of Granted to Issue Patent in Name of the Assignee", True, "PETITION: WON"], 
"P026" : ["Record a Petition Decision of Granted for Patent Term Adjustment after Issue", True, "PETITION: WON"], 
"P033" : ["Petition Decision - Granted", True, "PETITION: WON"], 
"PET." : ["Petition Entered", True, "PETITION: FILED"], 
"PET2" : ["Petition Entered", True, "PETITION: FILED"], 
"PREV" : ["Petition to Revive Application - Granted", True, "PETITION: WON"], 
"PTDE" : ["Petition Decision - Denied", True, "PETITION: LOST"], 
"PTDI" : ["Petition Decision - Dismissed", True, "PETITION: LOST"], 
"PTDI-1" : ["Petition Decision - Dismissed", True, "PETITION: LOST"], 
"PTGR" : ["Petition Decision - Granted", True, "PETITION: WON"], 
"PTGR-1" : ["Petition Decision - Granted", True, "PETITION: WON"], 

#>>> Count: FALSE
"TRIALPET" : ["Petition Requesting Trial", False], 
"ODPD" : ["ODM Petition Decision", False], 
"OPPT" : ["O.P. Petition Decision", False], 
"ODRWNFD" : ["Ommited Drawings.  Applicant has Petitioned that the Filing Date not be changed and the Petition has", False], 
"OSPECNFD" : ["Ommited Specification Pages.  Applicant has Petitioned that the Filing Date not be changed and the P", False], 
"TCPT" : ["TC Petition Decision", False], 
"PDCI" : ["Pet Dec Routed to Certificate of Corrections Branch", False], 
"PDDM" : ["Pet Dec Routed to ODM (PUBS)", False], 
"PDPH" : ["Pet Dec PPH Decision", False], 
"PDRT" : ["Pet Dec Routed to Tech Center", False], 
"PDTG" : ["Pet Dec Track 1 Grant", False], 

#================================================================================================
# EVENT TYPE: FAIP
#================================================================================================
#>>> Count: True
"RFAI" : ["Request for first action interview", True, "FAIP"], 
"SCIR" : ["Non COMpliant FAI (non pilot)", True, "NON-COMPLIANT"], 

#>>> Count: False
"FAIA" : ["Pilot-First Action Interview Office Action (FAI Step 2)", False], 
"FAOO" : ["Pilot-First Action (FA) without FA Interview (FAI Alternate Step 2)", False], 
"NCIR" : ["Noncompliant First Action Interview", False], 
"WRFAI" : ["Withdraw from first action interview", False], 
"PICO" : ["Pre-Interview Communication (FAI Step 1)", False], 

#================================================================================================
# EVENT TYPE: AFCP
#================================================================================================
#>>> Count: True
"AFAC" : ["After Final Consideration Program Additional Consideration and/or updated search", True, "AFCP: LOST"], 
"AFIR" : ["After Final Consideration Program Improper Request", True, "AFCP: DEFECTIVE"],
"AFNE" : ["After Final Consideration Program Amendment too Extensive", True, "AFCP: LOST"], 
"RAFC" : ["PILOT- Request for After Final Consideration Program", True, "AFCP"], 

#================================================================================================
# EVENT TYPE: INTERVIEWS
#================================================================================================
#>>> Count: True
"EXAC" : ["Interview Summary - Applicant Initiated - Conference", True, "INTERVIEW"], 
"EXAP" : ["Interview Summary - Applicant Initiated - Personal", True, "INTERVIEW"], 
"EXAT" : ["Interview Summary - Applicant Initiated - Telephonic", True, "INTERVIEW"], 
"EXEC" : ["Interview Summary - Examiner Initiated - Conference", True, "INTERVIEW"], 
"EXEP" : ["Interview Summary - Examiner Initiated - Personal", True, "INTERVIEW"], 
"EXET" : ["Interview Summary - Examiner Initiated - Telephonic", True, "INTERVIEW"], 
"EXIA" : ["Interview Summary- Applicant Initiated", True, "INTERVIEW"], 
"EXIE" : ["Interview Summary - Examiner Initiated", True, "INTERVIEW"], 
"EXIN" : ["Examiner Interview Summary Record (PTOL - 413)", True, "INTERVIEW"], 

#================================================================================================
# EVENT TYPE: PRELIMINARY AMENDMENT
#================================================================================================
#>>> Count: True
"A.PE" : ["Preliminary Amendment", True, "PRELIM"],
"PREAMND" : ["Preliminary Amendments", True, "PRELIM"], 
"CLAIM" : ["Claim Preliminary Amendment", True, "PRELIM"], 
"DRAWING" : ["Drawing Preliminary Amendment", True, "PRELIM"], 
"NPRL" : ["Non-Compliant Preliminary Amendment", True, "NON-COMPLIANT"], 

#================================================================================================
# EVENT TYPE: RCE
#================================================================================================
#>>> Count: True
"RCEX" : ["Request for Continued Examination (RCE)", True, "RCE"], 
"CPA-AMD" : ["RCE Amendment Informal or Non-Responsive", True, "NON-COMPLIANT"], 

#>>> Count: False
"ABN9" : ["Disposal for a RCE / CPA / R129", False], 

#================================================================================================
# EVENT TYPE: ABANDONMENT
#================================================================================================
#>>> Count: True
"ABN10" : ["Abandonment after Board of Appeals", True, "ABDN"], 
"ABN11" : [" Withdraw from Issue for Express Abandonment", True, "ABDN"], 
"ABN2" : ["Aband. for Failure to Respond to O. A.", True, "ABDN"], 
"ABN3" : ["Express Abandonment (during Examination)", True, "ABDN"], 
"ABN6" : ["Abandonment for Failure to Pay Issue Fee", True, "ABDN"], 
"ABN7" : ["Abandonment for Failure to Correct Drawings/Oath/NonPub Request", True, "ABDN"], 
"ABNF" : ["Abandonment -- Inc. Application under Rule 53(b) - Filing Fee Paid", True, "ABDN"], 
"ABNP" : ["Preexam Abandonment", True, "ABDN"], 
"ABNX" : ["Abandonment -- During Preexam Processing", True, "ABDN"],

#>>> Count: False
"EABN" : ["Letter of Express Abandonment Filed", False], 
"MABN" : ["Abandonment Mailed", False], 
"MABN10" : ["Mailing of Abandonment after Board of Appeals", False], 
"MABN2" : ["Mail Abandonment for Failure to Respond to Office Action", False], 
"MABN3" : ["Mail Express Abandonment (During Examination)", False], 
"MABN6" : ["Mail Abandonment for Failure to Pay Issue Fee", False], 
"MABN7" : ["Mail Abandonment for Failure to Correct Drawings/Oath", False], 
"MABNP" : ["Mail Preexam Abandonment", False], 
"NRAB" : ["Notice of Rescinded Abandonment in TCs", False], 
"P007" : ["Record Petition Decision of Granted to Withdraw from Issue for Express Abandonment", False], 
"P031" : ["Record Petition Decision of Granted to Withdraw ssue for Express Abandonment - with assigned Patent", False], 
"MNRAB" : ["Mail Notice of Rescinded Abandonment", False], 
"MP007" : ["Mail-Record Petition Decision of Granted to Withdraw from Issue for Express Abandonment", False], 
"MP031" : ["Mail-Record Petition Decision of Granted to Withdraw ssue for Express Abandonment - with assigned Pa", False], 
"PTDI-ABC" : ["Dismissed - Petition for express abandonment under rule 37 CRF 1.138(c)", False], 
"PTDI-ABD" : ["Dismissed -Petition for express abandonment under rule 37 CRF 1.138(d)", False], 
"PTGR-ABC" : ["Granted - Petition for express abandonment under rule 37 CRF 1.138(c)", False], 
"PTGR-ABD" : ["Granted - Petition for express abandonment under rule 37 CRF 1.138(d)", False], 
"WABN" : ["Withdraw Publication/Pre-Exam Abandon", False], 
"WPABN" : ["Withdraw Pre-Exam Abandon", False], 

#================================================================================================
# EVENT TYPE: APPEAL
#================================================================================================
#>>> Count: True
"AP.B" : ["Appeal Brief Filed", True, "APPEAL BRIEF"], 
"APRB" : ["Reply Brief Filed", True, "REPLY BRIEF"], 
"APEA" : ["Examiner's Answer to Appeal Brief", True, "EXAMINER ANSWER"], 
"AP.C" : ["Request for Pre-Appeal Conference Filed", True, "PRE-APPEAL CONFERENCE"], 
"APDA" : ["BPAI Decision - Examiner Affirmed", True, "APPEAL: LOST"],
"APDS" : ["Appeal Dismissed", True, "APPEAL: LOST"], 
"APDP" : ["BPAI Decision - Examiner Affirmed in Part", True, "APPEAL: DRAW"], 
"APDR" : ["BPAI Decision - Examiner Reversed", True, "APPEAL: WON"], 
"APBD" : ["Notice  --  Defective Appeal Brief", True, "APPEAL: DEFECTIVE"], 
"APBI" : ["Defective / Incomplete Appeal Brief Filed", True, "APPEAL: DEFECTIVE"], 
"APCD" : ["Pre-Appeals Conference Decision - Request Defective  ", True, "APPEAL: DEFECTIVE"], 
"APCA" : ["Pre-Appeals Conference Decision - Rejection Withdrawn", True, "PRE-APPEAL: WON"], 
"APCP" : ["Pre-Appeals Conference Decision - Proceed to BPAI", True, "PRE-APPEAL: LOST"], 
"APCR" : ["Pre-Appeals Conference Decision - Reopen Prosecution", True, "PRE-APPEAL: DRAW"], 
"N/AP" : ["Notice of Appeal Filed", True, "NOTICE OF APPEAL"], 

#>>> Count: False
"AP.C3" : ["Request for Pre-Appeal Conf. 3 Path", False], 
"AP_DK_M" : ["Docketing Notice Mailed to Appellant", False], 
"APAR" : ["Administrator Remand to the Examiner by BPAI", False], 
"APAS" : ["Assignment of Appeal Number", False], 
"APBR" : ["Appeal Brief Review Complete", False], 
"APCH" : ["Confirmation of Hearing by Appellant", False], 
"APE2" : ["2nd or Subsequent Examiner's Answer to Appeal Brief", False], 
"APEA" : ["Examiner's Answer to Appeal Brief", False], 
"APHC" : ["Hearing Completed", False], 
"APHT" : ["PTAB Oral Hearing Transcript", False], 
"APNH" : ["Notification of Appeal Hearing", False], 
"APOH" : ["Request for Oral Hearing", False], 
"APRB" : ["Reply Brief Filed", False], 
"APWD" : ["Appeal Awaiting BPAI Docketing", False], 
"APWH" : ["Waiver of Hearing by Appellant", False], 
"ARBP" : ["Appeal ready for BPAI review", False], 

#================================================================================================
# EVENT TYPE: SUSPENSIONS
#================================================================================================
#>>> Count: True
"AISP" : ["Suspension Letter- Applicant Initiated", True, "SUSPEND PROSECTION"], 

#================================================================================================
# EVENT TYPE: OFFICE ACTIONS
#================================================================================================
#>>> Count: True
"CTAV" : ["Advisory Action (PTOL-303)", True, "AA"], 
"CTEQ" : ["Quayle action", True, "EX PARTE QUAYLE"], 
"CTFR" : ["Final Rejection", True, "FOA"], 
"CTNF" : ["Non-Final Rejection", True, "NFOA"], 
"CTRS" : ["Restriction/Election Requirement", True, "RR"], 
"RJ.NG" : ["Rejection- New Grounds", True, "REJECTION - NEW GROUNDS"], 
"EX.R" : ["Reasons for Allowance", True, "NOA"], 

#>>> Count: False
"CTMS" : ["Miscellaneous Action with SSP", False], 

#================================================================================================
# EVENT TYPE: GENERAL ADMINISTRATIVE ITEMS
#================================================================================================
#application type flags
"ACPA" : ["Continuing Prosecution Application - Continuation (ACPA)", False], 
"ADDFLFEE" : ["Additional Application Filing Fees", False], 
"AERQ" : ["Accelerated Examination Request", False], 
"AF/D" : ["Affidavit(s) (Rule 131 or 132) or Exhibit(s) Received", False], 

"APPERMS" : ["Applicants have given acceptable permission for participating foreign ", False], 
"ASGMT" : ["The identification of one or more legal entities other than the inventor(s), each such legal entity ", False], 
"BCPA" : ["Workflow - Request for CPA - Begin", False], 
"BIG." : ["ENTITY STATUS SET TO UNDISCOUNTED (INITIAL DEFAULT SETTING OR STATUS CHANGE)", False], 
"BRCE" : ["Workflow - Request for RCE - Begin", False], 

#correspondence address
"C.AD" : ["Correspondence Address Change", False], 
"C.ADB" : ["Correspondence Address Change", False], 

#corrected notices
"C/N=" : ["Corrected Notice of Allowance", False], 
"C/NW" : ["Corrected Notice of Allowance", False], 
"CNOA" : ["Corrected Notice of Allowability", False], 
"COCM" : ["Certificate of Correction Memo", False], 

#filing particulars
"C600" : ["Supplemental Papers - Oath or Declaration", False], 
"C602" : ["Oath or Declaration Filed (Including Supplemental)", False], 
"C604" : ["Substitute Specification Filed", False], 
"C605" : ["Certified Translation of Specification Filed", False], 
"C614" : ["New or Additional Drawing Filed", False], 
"CCRDY" : ["Application ready for PDX access by participating foreign offices", False], 
"CDEN" : ["Post Issue Communication - Certificate of Correction Denied", False], 
"CFRPT" : ["Corrected filing receipt", False], 

#claims amendmentts
"CLMPCT1S" : ["Claim comparison Ch I - similar", False], 

#================================================================================================
# EVENT TYPE: UNCATEGORIZED
#================================================================================================

"COMP" : ["Application Is Now Complete", True, "COMPLETE"], 

"1750" : ["Record withdrawal of an application by the applicant.", False], 
"206I" : ["206I", False], 
"206R" : ["206R  ", False], 
"2091" : ["Disposal Flag Change", False], 
"2093" : ["Intermediate Flag Change", False], 
"210I" : ["210I", False], 
"210R" : ["210R  ", False], 
"2CCC" : ["PCT forwarded to CCC", False], 
"371COMP" : ["371 Completion Date", False], 
"CLTI" : ["Close TI", False], 
"CONV" : ["Pre_Exam Conversion", False], 
"CORRDRW" : ["Applicant has submitted new drawings to correct Corrected Papers problems", False], 
"CORRSPEC" : ["Applicant has submitted a new specification to correct Corrected Papers problems", False], 
"CPAP" : ["Corrected Paper", False], 
"CPICO" : ["Response to PICO-CFR 1.11", False], 
"CPYART19" : ["Copy of Article 19 Amendments", False], 
"CPYIA" : ["Copy of the International Application", False], 
"CRFE" : ["CRF Is Good Technically / Entered into Database", False], 
"CRFL" : ["CRF Disk Has Been Received by Preexam / Group / PCT", False], 
"CTSF" : ["PCT - Chapter 1 P210 / P237 (Full count)", False], 
"CTSH" : ["PCT - Chapter 1 P210 / P237 (Half Count)", False], 
"D1935" : ["Dispatch to FDC", False], 
"D5001" : ["Dispatch from OIPE to Corps - U-P-R-D Application", False], 
"D5003" : ["Dispatch from PCT Operations -Chapter I", False], 
"DOCK" : ["Case Docketed to Examiner in GAU", False], 
"DRWF" : ["Workflow - Drawings Finished", False], 
"EFIL" : ["Electronic Filing of Original Application Papers", False], 
"EIDS." : ["Electronic Information Disclosure Statement", False], 
"ELC_RVW" : ["Electronic Review", False], 
"EML_NTF" : ["Email Notification", False], 
"EML_NTR" : ["Email Notification", False], 
"EOSP" : ["to Close the A/R Record and Reset the Status for Expired Suspensions.", False], 
"EPRQ" : ["PGPubs early publication request", False], 
"EX.A" : ["Examiner's Amendment Communication", False], 
"EXP." : ["Expire Patent", False], 
"EXPRO" : ["EXPIRED PROVISIONAL", False], 
"FCPA" : ["Workflow - Request for CPA - Finish", False], 
"FEE." : ["Fee Payment Recorded (fees filed separately e.g. not with original papers, etc).", False], 
"FIDS" : ["Workflow - Informational Disclosure Statement - Finish", False], 
"FLFEE" : ["Payment of additional filing fee/Preexam", False], 
"FLRCPT.C" : ["Filing Receipt - Corrected", False], 
"FLRCPT.O" : ["Filing Receipt", False], 
"FLRCPT.R" : ["Filing Receipt - Replacement", False], 
"FLRCPT.U" : ["Filing Receipt - Updated", False], 
"FRCE" : ["Workflow - Request for RCE - Finish", False], 
"FTFB" : ["FITF set to NO - benefit/priority claim(s) to appln filed before 3/16/2013", False], 
"FTFC" : ["FITF set to YES - a claim w/ EFD on/after 3/16/2013 was filed", False], 
"FTFF" : ["FITF set to YES - 1.55/1.78 statement filed", False], 
"FTFI" : ["FITF set to NO - revise initial setting", False], 
"FTFP" : ["FITF set to NO - petition for earlier filing date before 3/16/2013 granted", False], 
"FTFR" : ["1.55/1.78 statement retracted", False], 
"FTFS" : ["FITF set to YES - revise initial setting", False], 
"FWDX" : ["Date Forwarded to Examiner", False], 
"GRCDK" : ["Rocket Docket Request Granted", False], 
"IACN" : ["Amendment Copying Claims - Not in Response to Examiner Suggesting Claims", False], 
"IDSC" : ["Information Disclosure Statement considered", False], 
"IDSPTA" : ["PTA statement filed under PTA1.704(d) with IDS", False], 
"IEXX" : ["Initial Exam Team nn", False], 
"IFEE" : ["Issue Fee Payment Received", False], 
"INCOR" : ["Interview Request Correction", False], 
"INFODSCL" : ["Information Disclosure Statements", False], 
"IPPC" : ["Incoming Request For Prosecution Pilot Conference", False], 
"IRCE" : ["Improper Request for Continued Examination", False], 
"IRFND" : ["Request for Refund", False], 
"L126" : ["Auto Referred by PALM Pre Exam", False], 
"L127" : ["Intentionally Referred by OIPE or L&R", False], 
"L128" : ["Cleared by L&R (LARS)", False], 
"L130" : ["Receipt of all Acknowledgement Letters", False], 
"L170" : ["Referred for NASA Property Rights review by L&R LARS", False], 
"L171" : ["Referred for DOE Property Rights review by L&R LARS", False], 
"L175" : ["Applicant response received", False], 
"L177" : ["30-day DOE or NASA Property Rights Letter mailed", False], 
"L178" : ["Response to 30-day Letter", False], 
"L181" : ["90-Day Letter to NASA", False], 
"L182" : ["90-Day Letter to DOE", False], 
"L183" : ["Acknowledgment of Receipt of 90-Day Letter", False], 
"L185" : ["No Government Interest - Patent to Issue to Applicant (No Letter to Applicant)", False], 
"L186" : ["Letter to Applicant - No government Interest / Patent to Issue", False], 
"L194" : ["Cleared by OIPE CSR", False], 
"L176" : ["Advisory Incomplete Statement mailed", False], 
"L196" : ["Referred by L&R for Third-Level Security Review. Agency Referral Letter Generated", False], 
"L197" : ["Receipt of Acknowledgment Letter", False], 
"L198" : ["Referred to Level 2 (LARS) by OIPE CSR", False], 
"L200" : ["Deferred", False], 
"LET." : ["Miscellaneous Incoming Letter", False], 
"LTDR" : ["Incoming Letter Pertaining to the Drawings", False], 
"M1551" : ["Payment of Maintenance Fee, 4th Year, Large Entity", False], 
"M1552" : ["Payment of Maintenance Fee, 8th Year, Large Entity", False], 
"M327" : ["Miscellaneous Communication to Applicant - No Action Count", False], 
"M327-1" : ["PUB Acknowledgement of NOA", False], 
"M327-4" : ["PUB Acknowledgement 1449", False], 
"M327-6" : ["PUB Acknowledgement Drawing", False], 
"M327-B" : ["PUB Notice of non-compliant IDS", False], 
"M327-D" : ["PUB Other miscellaneous communication to applicant", False], 
"M327-E" : ["BOA miscellaneous communication to applicant", False], 
"M327-G" : ["POST ISSUE OTHER COMMUNICATION TO APPLICANT- CERTIFICATE OF CORRECTION", False], 
"M327-O" : ["PUBS Notice Requiring Inventors Oath or Declaration", False], 
"M327-W" : ["PUBS Letter Withdrawing a Notice Requiring Inventors Oath or Declaration", False], 
"M844" : ["Information Disclosure Statement (IDS) Filed", False], 
"M844-1" : ["IDS with 1 mo. certification statement", False], 
"M856" : ["Letter Requesting Suspension of Prosecution", False], 
"M865" : ["Letter Requesting Interview with Examiner", False], 
"M865E" : ["Electronic request for Examiner Interview", False], 
"M903" : ["Notice of DO/EO Acceptance Mailed", False], 
"M905" : ["Notice of DO/EO Missing Requirements Mailed", False], 
"M912" : ["Notice of Insufficient Basic National Fee and/or Missing Copy of International Application", False], 
"M916" : ["Notice of DO/EO Defective Response Mailed.", False], 
"M923" : ["371 Supplemental Fees Missing - Form M923", False], 

#mailings
"MA.IX" : ["Mail of Withdraw of Informal Amendment Notice", False], 
"MAFAC" : ["Mail After Final Consideration Program Additional Consideration and/or updated search", False], 
"MAISP" : ["Mail Letter Suspending Prosecution at Applicant's Request", False], 
"MAPCA" : ["Mail Appeals conf. Rej. withdrawn", False], 
"MAPCD" : ["Mail Appeals conf. Request Defective", False], 
"MAPCP" : ["Mail Appeals conf. Proceed to BPAI", False], 
"MAPCR" : ["Mail Appeals conf. Reopen Prosec.", False], 
"MAPDA" : ["Mail BPAI Decision on Appeal - Affirmed", False], 
"MAPDN" : ["Mail - BPAI Decision 41.50(b) In IFW: 196(b) ", False], 
"MAPDP" : ["Mail BPAI Decision on Appeal - Affirmed in Part", False], 
"MAPDR" : ["Mail BPAI Decision on Appeal - Reversed", False], 
"MAPDS" : ["Appeal Dismissed - Mailed", False], 
"MAPE2" : ["Mail Supplemental Examiner's Answer", False], 
"MAPEA" : ["Mail Examiner's Answer", False], 
"MAPHT" : ["Mail PTAB Oral Hearing Transcript", False], 
"MC/N=" : ["Mail Corrected Notice of Allowance", False], 
"MC/NW" : ["Mail Corrected Notice of Allowance (Response period NOT restarted)", False], 
"MCNOA" : ["Mailing Corrected Notice of Allowability", False], 
"MCOCM" : ["Mail Certificate of Correction Memo", False], 
"MCPA-AMD" : ["Mail Notice of Informal or Non-Responsive RCE Amendment", False], 
"MCTAV" : ["Mail Advisory Action (PTOL - 303)", False], 
"MCTEQ" : ["Mail Ex Parte Quayle Action (PTOL - 326)", False], 
"MCTFR" : ["Mail Final Rejection (PTOL - 326)", False], 
"MCTMS" : ["Mail Miscellaneous Communication to Applicant", False], 
"MCTNF" : ["Mail Non-Final Rejection", False], 
"MCTRS" : ["Mail Restriction Requirement", False], 
"MEX.A" : ["Mail Examiner's Amendment", False], 
"MEX.R" : ["Mail Reasons for Allowance", False], 
"MEXAC" : ["Mail Interview Summary - Applicant Initiated - Conference", False], 
"MEXAP" : ["Mail Interview Summary - Applicant Initiated - Personal", False], 
"MEXAT" : ["Mail Interview Summary - Applicant Initiated - Telephonic", False], 
"MEXEC" : ["Mail Interview Summary - Examiner Initiated - Conference", False], 
"MEXEP" : ["Mail Interview Summary - Examiner Initiated - Personal", False], 
"MEXET" : ["Mail Interview Summary - Examiner Initiated - Telephonic", False], 
"MEXIA" : ["Mail Applicant Initiated Interview Summary", False], 
"MEXIE" : ["Mail Examiner Initiated Interview Summary", False], 
"MEXIN" : ["Mail Examiner Interview Summary (PTOL - 413)", False], 
"MFAIA" : ["Mail First Action Interview Office Action", False], 
"MFAOO" : ["Mail First Action without Interview", False], 
"MGRCDK" : ["Mail Rocket Docket Request Granted", False], 
"MM327" : ["Mail Miscellaneous Communication to Applicant", False], 
"MM327-1" : ["Mail PUB Acknowledgement of NOA", False], 
"MM327-4" : ["Mail PUB Acknowledgement 1449", False], 
"MM327-6" : ["Mail PUB Acknowledgement Drawing", False], 
"MM327-B" : ["Mail PUB Notice of non-compliant IDS", False], 
"MM327-D" : ["Mail PUB   other miscellaneous communication to applicant", False], 
"MM327-E" : ["Mail BOA miscellaneous communication to applicant", False], 
"MM327-G" : ["Mail Pub Notice re 312 amendment", False], 
"MM327-O" : ["Mail PUBS Notice Requiring Inventors Oath or Declaration", False], 
"MM327-W" : ["Mail PUBS Letter Withdrawing a Notice Requiring Inventors Oath or Declaration", False], 
"MN/=." : ["Mail Notice of Allowance", False], 
"MN/DR" : ["Mail  Formal Drawings Required", False], 
"MN271" : ["Mail Response to 312 Amendment (PTO-271)", False], 
"MNCDR" : ["Mail Notice of non-compliant drawings filed separately", False], 
"MNCIR" : ["Mail Noncompliant First Action Interview", False], 
"MNFEE" : ["Mail Notice of Required Fees Due", False], 
"MNPRL" : ["Mail Non-Compliant Preliminary Amendment", False], 
"MNRES" : ["Mail Notice of Restarted Response Period", False], 
"MODPD" : ["Mail ODM Petition Decision", False], 
"MODPD:4" : ["Mail GRANTED - Decision to Accept Color Drawings under 37 CFR 1.84(a)(2)", False], 
"MODPD:8" : ["Mail Letter Withdrawing a Notice Requiring Inventor Oath or Declaration", False], 
"MOPPT" : ["Mail O.P. Petition Decision", False], 
"MP002" : ["Mail-Record Petition Decision of Granted to Suspend an Action", False], 
"MP003" : ["Mail-Record Petition Decision of Granted to Make Special", False], 
"MP005" : ["Mail-Record Petition Decision of Granted to Accept Delayed Payment of Issue Fee", False], 
"MP006" : ["Mail-Record Petition Decision of Granted to Withdraw from Issue", False], 
"MP015" : ["Mail-Record Petition Decision of Granted to Withdraw from Issue - with assigned Patent NO.", False], 
"MP023" : ["Mail-Record a Petition Decision of Granted to Issue Patent in Name of the Assignee", False], 
"MP026" : ["Mail-Record a Petition Decision of Granted for Patent Term Adjustment after Issue", False], 
"MP033" : ["Mail-Petition Decision - Granted", False], 
"MP206" : ["Mail PCT Chapter I Form 206", False], 
"MP210" : ["Mail International Search Report", False], 
"MP327" : ["Mail Acknowledgement of Priority Papers", False], 
"MP327-P" : ["Mail Acknowledgement of Priority Papers-Pub", False], 
"MP3DS" : ["Mail Third Party IDS communication", False], 
"MPCRO" : ["Mail Prosecution Conference Pilot -  Reopen Prosecution", False], 
"MPCRP" : ["Mail Prosecution Conference Pilot -  Rejection Proper", False], 
"MPDCI" : ["Mail Pet Dec Routed to Certificate of Corrections Branch", False], 
"MPDDM" : ["Mail Pet Dec Routed to ODM (PUBS)", False], 
"MPDPH" : ["Mail Pet Dec PPH Decision", False], 
"MPDRT" : ["Mail Pet Dec Routed to Tech Center", False], 
"MPDTG" : ["Mail Pet Dec Track 1 Grant", False], 
"MPDX" : ["Priority Document Exchange Notice Mailed", False], 
"MPEN" : ["Mail Pre-Exam Notice", False], 
"MPETDEC" : ["Petition Decision Notice Mailed", False], 
"MPFA" : ["Mail Pre-interview First Office Action", False], 
"MPICO" : ["Mail Pre-Interview Communication", False], 
"MPREV" : ["Mail-Petition to Revive Application - Granted", False], 
"MPTDE" : ["Mail-Petition Decision - Denied", False], 
"MPTDI" : ["Mail-Petition Decision - Dismissed", False], 
"MPTDI-1" : ["Mail-Petition Decision - Dismissed", False], 
"MPTGR" : ["Mail-Petition Decision - Granted", False], 
"MPTGR-1" : ["Mail-Petition Decision - Granted", False], 
"MQPRO" : ["Mail Quick Path IDS Reopen Prosecution", False], 
"MQRCE" : ["Mail Quick Path IDS Examiner-directed entry of RCE", False], 
"MR327" : ["RX - Mail Miscellaneous Communication to Applicant", False], 
"MREXN" : ["RX - Mail Examiner Interview Summary Record", False], 
"MSCIR" : ["Mail Noncompliant FAI", False], 
"MSCSS" : ["Misc Special Soft Scanning- No Mailing", False], 
"MTCPT" : ["Mail TC Petition Decision", False], 
"MW/AC" : ["Mail Notice of Withdrawn Action", False], 

#other administrative things
"MICR" : ["Applicant Has Filed a Verified Statement of Micro Entity Status in Compliance with 37 CFR 1.29", False], 
"ML170" : ["Request for Applicant Statement Regarding Potential NASA Interest (45-Day Letter) Mailed", False], 
"ML171" : ["Request for Applicant Statement Regarding Potential DOE Interest  (45-Day Letter) Mailed", False], 
"ML196" : ["Agency Referral Letter Mailed", False], 
"MLIB" : ["Record Copy Mailed", False], 

"N/=." : ["Notice of Allowance Data Verification Completed", False], 
"N/DR" : ["Formal Drawings Required", False], 
"N084" : ["Issue Fee Payment Verified", False], 
"N271" : ["Response to Amendment under Rule 312", False], 
"N423" : ["Post Issue Communication - Certificate of Correction", False], 
"NCDR" : ["Notice of non-compliant drawings filed separately", False], 
"NFEE" : ["Fee (additional) Due Notice", False], 
"NINA" : ["Mail Notice of Informal or Non-Responsive Amendment", False], 
"NPICO" : ["Response to PICO-no interview", False], 
"NRE." : ["Notice of Reissue Published in Official Gazette", False], 
"NRES" : ["Letter Restarting Period for Response (i.e. Letter re References)", False], 
"OATHDECL" : ["A statement by one or more inventors satisfying the requirement under 35 USC 115, Oath of the Applic", False], 
"ODPD:4" : ["GRANTED - Decision to Accept Color Drawings under 37 CFR 1.84(a)(2)", False], 
"ODPD:8" : ["Letter Withdrawing a Notice Requiring Inventor Oath or Declaration", False], 
"OIPE" : ["Application Dispatched from OIPE", False], 
"OMIT" : ["Notice of Omitted Items", False], 
"P028" : ["Adjustment of PTA Calculation by PTO", False],

#PCT-related tasks
"P102" : ["Notification Concerning Payment of Fees", False], 
"P105" : ["Notification of Intntl. Appl. Number and Intntl. Filing Date", False], 
"P106" : ["Invitation to Correct Defects", False], 
"P107" : ["Notification of Non-Inclusion of Drawings", False], 
"P109" : ["Notification of Decision Concerning Request for Rectification", False], 
"P110" : ["Invitation to Correct Priority Date or Cancel Priority Claim", False], 
"P111" : ["Notification of Correction or Cancellation of Priority Claim", False], 
"P113" : ["Request for Recording a Change", False], 
"P114" : ["Notification on Decision of Confirmation of Incorporation by Reference Of Element", False], 
"P123" : ["Notification Concerning Representation", False], 
"P124" : ["Notification of Defective POA or Defective Revocation of POA", False], 
"P132" : ["Miscellaneous Communication", False], 
"P133" : ["Invitation to Pay Fees and Late Fee", False], 
"P136" : ["Notification of Withdrawal", False], 
"P146" : ["Notification of Ex-officio correction", False], 
"P151" : ["Notification of Transmittal of Intntl. Appl. to IB as RO", False], 
"P202" : ["Notification of Receipt of Search Copy", False], 
"P206" : ["PCT - Chapter 1 Form 206 (Invitation to Pay Additional Fees)", False], 
"P210" : ["International Search Report Ready to be Mailed", False], 
"P217" : ["Notification of Decision Concerning Req. for Rectification", False], 
"P224" : ["General Communication - No Other Forms Applicable", False], 
"P237" : ["ISA Written Opinion", False], 
"P327" : ["Priority Paper Acknowledgement", False], 
"P327-P" : ["Acknowledgement of Priority Papers-Pub", False], 
"P3DS" : ["Third Party IDS communication", False], 
"P574" : ["PARALEGAL OR ELECTRONIC TERMINAL DISCLAIMER APPROVED ", False], 
"P575" : ["Paralegal TD Not accepted", False], 
"PACC" : ["Exam. Ans. Review Complete", False], 
"PCH1T" : ["PCT Ch. 1 Transcription", False], 
"PCRD" : ["Prosecution Conference Pilot -  Request Defective", False], 
"PCRO" : ["Prosecution Conference Pilot -  Reopen Prosecution", False], 
"PCRP" : ["Prosecution Conference Pilot -  Rejection Proper", False], 
"PCS" : ["A cover letter for a provisional application, containing much of the information that would otherwis", False], 
"PCTFR" : ["PCT Formality Review", False], 
"PD.FAIL" : ["Final PDX/DAS request for priority document has failed", False], 
"PD.RECVD" : ["Priority document has successfully retrieved via PDX/DAS", False], 
"PDREQUST" : ["Request from applicant for the USPTO to retrieve the Priority Document", False], 
"PFA" : ["PILOT - Pre-Interview Communication", False], 

"PG-ISSUE" : ["PG-Pub Issue Notification", False], 
"PG-PB-DT" : ["PG-Pub Notice of new or Revised projected publication date", False], 
"PG-RQST" : ["PG-Pub Request", False], 
"PG-SUBM" : ["PG-Pub Submission", False], 

"PGM/" : ["Recordation of Patent Grant Mailed", False], 
"PGM/D" : ["Recordation of Patent Grant Mailed - Duplicate Letters Patent Mailed", False], 
"PGM/R" : ["Recordation of Patent Grant Mailed - Remailed", False], 
"PGPC" : ["Sent to Classification Contractor", False], 
"PGPW" : ["Waiting LR clearance", False], 

"PILS" : ["Application Is Considered Ready for Issue", False], 
"POSTCARD" : ["A self-addressed post card (having the applicant\'s address) received with a patent application for t", False], 
"PRIR" : ["Paralegal Reissue Review Complete", False], 
"PST_CRD" : ["Mail Post Card", False], 
"PTA.RFE" : ["Patent Term Adjustment - Ready for Examination", False], 
"PTAC" : ["Patent Issue Date Used in PTA Calculation", False], 
"PUBTC" : ["Pubs Case Remand to TC", False], 
"QPREQ" : ["Quick Path IDS Request", False], 
"QPRO" : ["Quick Path IDS Reopen Prosecution", False], 
"QRCE" : ["Quick Path IDS Examiner-directed entry of RCE", False], 
"R155X" : ["1.55/1.78 Indicator set", False], 
"R48ACLT" : ["Letter Accepting Correction of Inventorship Under Rule 1.48", False], 
"R48RJLT" : ["Letter Rejecting Correction of Inventorship Under Rule 1.48", False], 
"RBPAI" : ["RESTORED TO BOARD DECISION STATUS", False], 
"RCAP" : ["Reference capture on IDS", False], 
"RCDT" : ["Receipt Date", False], 
"REM." : ["Maintenance Fee Reminder Mailed", False], 
"ROIPE" : ["Application Return TO OIPE", False], 
"ROST" : ["RO complete, placed in storage", False], 
"RPCP" : ["Prosecution Pilot Conference Conducted", False], 
"RPICO" : ["Response to PICO-Request", False], 
"RPLDRWG" : ["Replacement Drawings (Changes the Filing Date)", False], 
"RQPR" : ["Request for Foreign Priority (Priority Papers May Be Included)", False], 
"RRCDK" : ["Rocket Docket request", False], 
"RU47" : ["Rule 47 / 48 Correction of Inventorship Papers Filed", False], 
"SB39ACPR" : ["Letter Accepting Permission for Application Access by Foreign IPO", False], 
"SB39RJPR" : ["Letter Rejecting Permission for Application Access by Foreign IPO", False], 
"SB69ACPR" : ["Letter Accepting Permission for Search Results Access by Foreign IPO", False], 
"SB69RJPR" : ["Letter Rejecting Permission for Search Results Access by Foreign IPO", False], 
"SCAN" : ["IFW Scan & PACR Auto Security Review", False], 
"SEQLIST" : ["A set of symbols and procedures, provided to the PTO on a set of computer listings, that describe in", False], 
"SES" : ["Small Entity Statement (37 CFR 1.27)", False], 
"SMAL" : ["Applicant Has Filed a Verified Statement of Small Entity Status in Compliance with 37 CFR 1.27", False], 
"SPECIFIC" : ["A  document that contains, at least in part, a written description of an invention, and of the manne", False], 
"SQPR" : ["SEQUENCE ERRORS", False], 
"SREXR141" : ["PTO/SB/69-Authorize EPO Access to Search Results", False], 
"SUBSPEC" : ["Substitute Specification", False], 
"T1GR" : ["Track 1 Request Granted", False], 
"T1OFF" : ["track 1 OFF", False], 
"T1ON" : ["track 1 ON ", False], 
"TCBP" : ["TC completion of return order", False], 
"TCPB" : ["Printer Rush- No mailing", False], 
"TCRD" : ["Return of Undocketed appeal to the TC", False], 
"TCWD" : ["Appeal ready for BPAI docketing", False], 
"TDP" : ["terminal disclaimer fee paid", False], 
"TF01" : ["TF01", False], 
"TF02" : ["TF02", False], 
"TF03" : ["TF03", False], 
"TF04" : ["TF04 ", False], 
"TF05" : ["TF05  ", False], 
"TF06" : ["TF06  ", False], 
"TF08" : ["TF08  ", False], 
"TFPR" : ["Certified Translation of Foreign Priority Document", False], 
"TRIALFWD" : ["Termination or Final Written Decision", False], 
"TRNCLAIM" : ["Translation of Claims into English", False], 
"TRNIA" : ["Translation of the international application into English", False], 
"TRNSPEC" : ["Translation of Specification into English", False], 
"TSSCOMP" : ["IFW TSS Processing by Tech Center Complete", False], 
"VFEE" : ["Reverse Issue Fee", False], 
"W/AC" : ["Withdrawing/Vacating Office Action Letter", False], 
"W/N=" : ["Withdrawal of Notice of Allowance", False], 
"W/OA" : ["Pre-Exam Office Action Withdrawn", False], 
"WFIS" : ["Withdrawal Patent Case from Issue", False], 
"WPIR" : ["Issue Notification Mailed", False], 
"WROIPE" : ["Application Return from OIPE", False], 
"X/DR" : ["Correction - Drawing NOT Required", False], 
"XT/G" : ["Request for Extension of Time - Granted", False], 
}